#!/bin/bash

# Only restart spamd if sa-update returns 0, meaning it updated the rules

/usr/bin/sa-update | logger -i -p mail.info || exit $?

svc -d /var/qmail/supervise/spamd | logger -i -p mail.info
svc -t /var/qmail/supervise/spamd | logger -i -p mail.info
svc -u /var/qmail/supervise/spamd | logger -i -p mail.info
