#!/bin/bash

# Only restart spamd if sa-update returns 0, meaning it updated the rules

/usr/bin/sa-update | logger -i -p mail.info

if [ "${PIPESTATUS[0]}" != "0" ]; then
  exit ${PIPESTATUS[0]}
fi

service spamd restart
